config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'customers#new', as: :admin_root
  resources :rentals
  resources :vehicles
  resources :customers do
    resources :rentals
  end
  get 'all_rental_payment_due', to: 'rentals#all_rental_payment_due', as: :all_rental_payment_due
  get 'search_customer', to: 'customers#search_customer'
  get 'search_vehicle', to: 'vehicles#search_vehicle'
end

app/models/customer.rb
class Customer < ApplicationRecord
  self.primary_key = 'cust_id'
  has_one :rental

  scope :search, ->(val){ where("name like ? OR (cust_id::text LIKE ?)", "%#{val}%", "%#{val}%").order(name: :asc) }
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end


  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def search_customer
    @search = Customer.search(params[:search])
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :phone)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.haml
%h1 Listing Customers


%ul.nav.navbar-nav
  %li.searchwrap
    .searchbox
      = form_tag search_customer_path, method: :get do
        = text_field_tag "search", nil, placeholder: "Company Search..."
        %span.searchicon
          %i.fa.fa-search
%table
  %tr
    %th Customer ID
    %th Name
    %th Remaining Balance
  - @customers.each do |customer|
    %tr
      %td= customer.id
      %td= customer.name
      %td= remaining_balance(Rental.find_by(cust_id: customer.cust_id))

app/views/customers/new.html.haml
%h1 New Customer
= form_with model: @customer do |form|
  %div
    = form.label :name
    %br/
    = form.text_field :name
  %div
    = form.label :phone
    %br/
    = form.text_field :phone
  %div
    = form.submit

app/views/customers/search_customer.html.haml
%h1 Search Customers

%table
  %tr
    %th Customer ID
    %th Name
    %th Remainig Balance
  - @search.each do |customer|
    %tr
      %td= customer.id
      %td= customer.name
      %td= customer.phone

app/views/customers/show.html.haml
%h1= @customer.name
%p= @customer.phone
%ul
  %li= link_to 'Add a Rental', new_customer_rental_path(@customer)
  %li= link_to "Destroy", customers_path(@customer), |
      method: :delete,                           |
      data: { confirm: "Are you sure?" }         |