config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'customers#new', as: :admin_root
  resources :rentals
  resources :vehicles
  resources :customers do
    resources :rentals
  end
  get 'all_rental_payment_due', to: 'rentals#all_rental_payment_due', as: :all_rental_payment_due
  get 'search_customer', to: 'customers#search_customer'
  get 'search_vehicle', to: 'vehicles#search_vehicle'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  self.primary_key = 'vehicle_id'
  has_one :rental
  #enum vehicle_type: ["compact", "medium", "large", "suv", "truck", "van"]
  enum category: ["basic", "luxury"]
  default_scope { order(created_at: :asc) }

  #before_create :generate_vehicle_id

  scope :search, ->(val){ where("description LIKE ? OR (vehicle_id LIKE ?)", "%#{val}%", "%#{val}%") }

  # def generate_vehicle_id
  #   self.vehicle_id = (0...17).map { (65 + rand(26)).chr }.join
  # end
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord

  def self.id_with_names
    vehicle_types = {}
    self.all.order(id: :asc).each do |vehicle_type|
      vehicle_types[vehicle_type.name.sub(" ", "_").to_sym] = vehicle_type.id
    end
    vehicle_types
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def index
    @vehicles = Vehicle.all
  end


  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    puts "===========BEFORE#{@vehicle.inspect}=============="
    if @vehicle.save!
      puts "===========AFTER#{@vehicle.inspect}=============="
      redirect_to @vehicle
    else
      render :new
    end
  end

  def show

  end

  def search_vehicle
    @search = Vehicle.search(params[:search])
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:vehicle_id, :description, :year, :category, :vehicle_type)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper

  # def vehicle_years
  #   options_for_select([['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['Unlimited', 'unlimited']], f.object.persisted? ? f.object.photo_storage : nil)
  # end

  # def avg_daily_price
  # 	Vecil
  # end	
end

app/views/vehicles/index.html.haml
%h1 Listing Vehicles


%ul.nav.navbar-nav
  %li.searchwrap
    .searchbox
      = form_tag search_vehicle_path, method: :get do
        = text_field_tag "search", nil, placeholder: "Company Search..."
        %span.searchicon
          %i.fa.fa-search
%table
  %tr
    %th VIN ID
    %th Description
    %th Average Daily Price
  - @vehicles.each do |vehicle|
    %tr
      %td= vehicle.id
      %td= vehicle.description
      %td= Rental.where(vehicle_id: vehicle.vehicle_id).avg(:total_amount)

app/views/vehicles/new.html.haml
%h1 New Vehicle
= form_with model: @vehicle do |form|
  %div
    = form.label :Descrption
    %br/
    = form.text_field :description
  %br/
  %div
    = form.label :Year
    %br/
    = form.select :year, ['2015', '2016', '2017', '2018', '2019', '2020']
  %br/
  %div
    = form.label :Category
    %br/
    = form.select :category, Vehicle.categories.keys
  %br/
  %div
    = form.label :VehicleType
    %br/
    = form.select :vehicle_type, VehicleType.id_with_names
  %br/
  %div
    = form.submit

app/views/vehicles/search_vehicle.html.haml
%h1 Search Vehicle

%table
  %tr
    %th VIN ID
    %th Description
    %th Average Daily Price
  - @search.each do |vehicle|
    %tr
      %td= vehicle.id
      %td= vehicle.description
      %td= Rental.where(vehicle_id: vehicle.vehicle_id).avg(:total_amount)